version: '3.7'
services:
  database:
    image: postgres:alpine
    restart: always
    environment: 
      - POSTGRES_USER={$POSTGRES_USER}
      - POSTGRES_PASSWORD={$POSTGRES_PASSWORD}
      - POSTGRES_DB={$POSTGRES_DB}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
     - "${DATABASE_PORT}:5432"
    networks: 
      - app-network
  backend:
    build: ./backend
    restart: always
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on: 
      - database
    networks:
      - app-network
  frontend:
    restart: always
    build: ./frontend
    ports: 
      - "${FRONTEND_PORT}:8080"
    depends_on: 
      - backend
    links:
      - 'backend'
    networks:
      - app-network
networks:
  app-network:
